### PR TITLE
conf: Mark layer as compatible with Mickledore.

### PR DESCRIPTION
**Pull request by MagneFire**
This is needed as part of https://github.com/AsteroidOS/asteroid/issues/245.

### CODE REVIEW

**Review by beroset — APPROVED** [review]
Thanks for catching this!

**Review by FlorentRevest — APPROVED** [review]

**Review by beroset — APPROVED** [review]
Could we make this "kirkstone mickledore" instead?  I don't think there's anything that would not be compatible with either.

**Comment by beroset** [comment]
Good changes, thanks!

**Comment by FlorentRevest** [comment]
I sort of anticipate that things will start to break at one point against kirkstone just because we won't be testing it and anything untested is probably broken. But since it probably eases the migration, that's fine by me

**Pull request merged**
